export const categories = [
  {
    name: "Categorized Products",
    subcategories: [
      {
        name: "",
        categoryName: [
          {
            id: "1",
            image: "/placeholder.svg",
            title: "Drone Parts",
            description: "High-quality components for custom drone builds",
            price: "$499",
            products: [
              {
                id: "dp1",
                image:
                  "https://th.bing.com/th/id/OIP.E5Na9tJDw-F9jUJAUwQYAgHaE8?rs=1&pid=ImgDetMain",
                name: "Nano Motors",
                description: "Ultra-efficient motors for compact drones",
                price: "$49.99",
              },
              {
                id: "dp2",
                image: "/placeholder.svg",
                name: "Nano Drone",
                description: "Ready-to-fly miniature drone for indoor use",
                price: "$129.99",
              },
              {
                id: "dp3",
                image: "/placeholder.svg",
                name: "Nano Frames",
                description: "Lightweight and durable drone frames",
                price: "$39.99",
              },
              {
                id: "dp4",
                image: "/placeholder.svg",
                name: "BLDC Motors",
                description: "Brushless motors for efficient drone flight",
                price: "$59.99",
              },
              {
                id: "dp5",
                image: "/placeholder.svg",
                name: "Propellers",
                description: "High-performance propellers for stable flight",
                price: "$19.99",
              },
              {
                id: "dp6",
                image: "/placeholder.svg",
                name: "Controllers GPS",
                description: "Advanced GPS-enabled controllers for drones",
                price: "$149.99",
              },
              {
                id: "dp7",
                image: "/placeholder.svg",
                name: "Frames",
                description: "Strong and lightweight frames for drones",
                price: "$79.99",
              },
              {
                id: "dp8",
                image: "/placeholder.svg",
                name: "Remote Controllers",
                description: "High-precision remote controllers for drones",
                price: "$99.99",
              },
              {
                id: "dp9",
                image: "/placeholder.svg",
                name: "Distribution Boards",
                description: "Reliable power distribution boards for drones",
                price: "$34.99",
              },
              {
                id: "dp10",
                image: "/placeholder.svg",
                name: "Drone Accessories",
                description: "Essential add-ons for drone customization",
                price: "$24.99",
              },
              {
                id: "dp11",
                image: "/placeholder.svg",
                name: "Batteries",
                description:
                  "Long-lasting batteries for extended drone flights",
                price: "$59.99",
              },
            ],
          },
          {
            id: "2",
            image: "/placeholder.svg",
            title: "Electronic Parts",
            description:
              "Essential electronic components for various applications",
            price: "$399",
            products: [
              {
                id: "ep1",
                image: "/placeholder.svg",
                name: "Controllers chip",
                description: "High-performance chips for control systems",
                price: "$19.99",
              },
              {
                id: "ep2",
                image: "/placeholder.svg",
                name: "Controllers Kit",
                description: "Complete controller kits for robotics projects",
                price: "$89.99",
              },
              {
                id: "ep3",
                image: "/placeholder.svg",
                name: "Passive Components",
                description:
                  "Resistors, capacitors, and inductors for circuits",
                price: "$9.99",
              },
              {
                id: "ep4",
                image: "/placeholder.svg",
                name: "Tools",
                description: "Precision tools for electronic assembly",
                price: "$29.99",
              },
              {
                id: "ep5",
                image: "/placeholder.svg",
                name: "Cables",
                description: "Durable cables for electronic connections",
                price: "$14.99",
              },
              {
                id: "ep6",
                image: "/placeholder.svg",
                name: "Connectors",
                description: "Reliable connectors for circuit board assembly",
                price: "$7.99",
              },
              {
                id: "ep7",
                image: "/placeholder.svg",
                name: "Batteries",
                description: "Rechargeable batteries for electronic devices",
                price: "$24.99",
              },
              {
                id: "ep8",
                image: "/placeholder.svg",
                name: "Mechanical Parts",
                description: "Various mechanical components for robotics",
                price: "$49.99",
              },
            ],
          },
          {
            id: "3",
            image: "/placeholder.svg",
            title: "Mechanical Parts",
            description: "Durable mechanical parts for robotics and drones",
            price: "$549",
            products: [
              {
                id: "mp1",
                image: "/placeholder.svg",
                name: "Wheels",
                description: "High-traction wheels for robotic applications",
                price: "$39.99",
              },
              {
                id: "mp2",
                image: "/placeholder.svg",
                name: "Wheel Base",
                description: "Stable wheel bases for robot movement",
                price: "$59.99",
              },
              {
                id: "mp3",
                image: "/placeholder.svg",
                name: "Robo Frames",
                description: "Sturdy frames for robotic builds",
                price: "$79.99",
              },
              {
                id: "mp4",
                image: "/placeholder.svg",
                name: "Couplers",
                description: "Precision couplers for mechanical linkages",
                price: "$14.99",
              },
              {
                id: "mp5",
                image: "/placeholder.svg",
                name: "Tools",
                description: "Essential tools for mechanical assembly",
                price: "$34.99",
              },
              {
                id: "mp6",
                image: "/placeholder.svg",
                name: "Bars",
                description: "Metal and composite bars for structural support",
                price: "$29.99",
              },
              {
                id: "mp7",
                image: "/placeholder.svg",
                name: "Nut-Bolts",
                description: "High-quality nuts and bolts for assembly",
                price: "$9.99",
              },
              {
                id: "mp8",
                image: "/placeholder.svg",
                name: "Composite Sheets",
                description: "Lightweight yet strong composite sheets",
                price: "$49.99",
              },
              {
                id: "mp9",
                image: "/placeholder.svg",
                name: "Metal Sheets",
                description: "Durable metal sheets for mechanical applications",
                price: "$59.99",
              },
            ],
          },
          {
            id: "4",
            image: "/placeholder.svg",
            title: "Agricultural Drone Parts",
            description: "Specialized drone components for agricultural use",
            price: "$599",
            products: [
              {
                id: "adp1",
                image: "/placeholder.svg",
                name: "Drone Accessories",
                description: "Essential accessories for agricultural drones",
                price: "$34.99",
              },
              {
                id: "adp2",
                image: "/placeholder.svg",
                name: "Nozzles",
                description: "High-precision nozzles for pesticide spraying",
                price: "$19.99",
              },
              {
                id: "adp3",
                image: "/placeholder.svg",
                name: "Propellers",
                description: "Durable propellers for agricultural drones",
                price: "$24.99",
              },
              {
                id: "adp4",
                image: "/placeholder.svg",
                name: "Frames",
                description: "Reinforced frames for agricultural drones",
                price: "$89.99",
              },
            ],
          },
        ],
      },
    ],
  },
];
